export default function SobreNos() {
    return (
        <section className="p-4" id="sobre_nos">
                <div className="text-center">
                    <h2 className="m-5 text-3xl font-bold">Sobre nós</h2>
                </div >
                <p className="text-sl md:text-lg">BEM-VINDO AO AUTODIAG, O SEU ASSISTENTE VIRTUAL DE DIAGNÓSTICOS AUTOMOTIVOS!</p>
                <p className="text-sl md:text-lg">NA AUTODIAG, REVOLUCIONAMOS A MANEIRA COMO VOCÊ CUIDA DO SEU VEÍCULO. NOSSO APLICATIVO INOVADOR UTILIZA A INTELIGÊNCIA ARTIFICIAL PARA FORNECER DIAGNÓSTICOS PRECISOS E RÁPIDOS ATRAVÉS DE CHATBOTS. COM APENAS ALGUNS CLIQUES, VOCÊ PODE DESCREVER OS PROBLEMAS QUE ESTÁ ENFRENTANDO COM SEU CARRO, E NOSSO CHATBOT INTELIGENTE ANALISARÁ OS SINTOMAS PARA OFERECER UM DIAGNÓSTICO CONFIÁVEL.</p>
                <p className="text-sl md:text-lg">MAS NÃO PARAMOS POR AÍ! ALÉM DE IDENTIFICAR O PROBLEMA, A AUTODIAG AJUDA VOCÊ A ENCONTRAR AS MELHORES OPÇÕES DE ORÇAMENTO PARA O REPARO DO SEU VEÍCULO. CONECTAMOS VOCÊ COM OFICINAS E MECÂNICOS DE CONFIANÇA, OFERECENDO COTAÇÕES TRANSPARENTES E COMPETITIVAS. NOSSO OBJETIVO É TORNAR O PROCESSO DE MANUTENÇÃO AUTOMOTIVA SIMPLES, CONVENIENTE E ECONÔMICO.</p>
                <p className="text-sl md:text-lg">NOSSA MISSÃO É PROPORCIONAR UMA EXPERIÊNCIA LIVRE DE ESTRESSE E CONFIÁVEL PARA OS PROPRIETÁRIOS DE VEÍCULOS, UTILIZANDO TECNOLOGIA DE PONTA PARA DIAGNÓSTICOS AUTOMOTIVOS E SERVIÇOS DE ORÇAMENTO. QUEREMOS GARANTIR QUE SEU CARRO ESTEJA SEMPRE EM ÓTIMO ESTADO, SEM COMPLICAÇÕES E COM TOTAL TRANSPARÊNCIA.</p>
        </section>
    )
}